### ISSUE TITLE
With the latest version of Docker Desktop the images cannot be retrieved (while the containers still can)

### ISSUE THREAD

**Issue by cegeka-jd** [eclipse-linuxtools/org.eclipse.linuxtools#318] opened 2024-02-14 13:08 UTC
With the latest version of Docker Desktop, at the time of this writing v4.27.2, the docker images cannot be listed (while the containers still can)

Details and exception:

eclipse.buildId=4.30.0.20231201-1200
java.version=21.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=nl_BE
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/C:/cegeka/workspaces/jbaas/container-images/ -product org.eclipse.epp.package.jee.product

org.eclipse.core.jobs
Error
Wed Feb 14 13:38:35 CET 2024
An internal error occurred during: "Refreshing Images...".

java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "s" is null
	at org.eclipse.linuxtools.docker.core.DockerException.calculateMessage(DockerException.java:56)
	at org.eclipse.linuxtools.docker.core.DockerException.<init>(DockerException.java:33)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.listImages(DockerConnection.java:1136)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.getImages(DockerConnection.java:1070)
	at org.eclipse.linuxtools.internal.docker.ui.commands.RefreshConnectionHandler$2.run(RefreshConnectionHandler.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

![2024-02-14 14_05_09-](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/38648332/f30cf319-22f3-4491-91e9-dc2a55d2eb92)

**Comment by akurtakov** [comment] 2024-02-20 06:02
Duplicate of https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/issues/309

**Closed by akurtakov** 2024-02-20 06:02 UTC
