### ISSUE TITLE
Docker Tooling unable to connect to backend on Apple Silicon Mac

### ISSUE THREAD

**Issue by tcwan** [eclipse-linuxtools/org.eclipse.linuxtools#61] opened 2022-06-15 23:29 UTC
Docker Desktop for macOS 4.6.1, on Monterey 12.3 running on M1 Mac.

Docker Tooling in AArch64 version of Eclipse Embedded for C/C++ is unable to connect to Docker Backend (via Unix socket).

Same setup with x86_64 version of Eclipse Embedded for C/C++ (running via Rosetta) is able to connect and execute build in Docker image.

Tested with 2022-03, and 2021-12. Docker Tooling is not working on AArch64 Eclipse.

**Comment by tcwan** [comment] 2022-06-15 23:31
This is a re-post of [my previous report](https://marketplace.eclipse.org/comment/7937#comment-7937) in Eclipse Marketplace.

**Comment by akurtakov** [comment] 2022-06-16 02:29
I am not aware of anyone of the developers having Mac M1 so we will need you to investigate the issue and ideally come with a patch for that.

**Comment by tcwan** [comment] 2022-06-21 08:27
> I am not aware of anyone of the developers having Mac M1 so we will need you to investigate the issue and ideally come with a patch for that.

Hmm. Sorry I don't know Eclipse or Java well enough to troubleshoot. I'm just using it for the IDE. It's rather strange that it only affected AArch64 builds for M1 Macs though. It worked fine on Intel Macs (and also via Rosetta but I'm guessing that it adds unnecessary overheads).

**Comment by akurtakov** [comment] 2022-06-23 16:18
I think I have an idea why it fails. Docker plugin uses libraries that deal with native code and probably some of them don't support Mac M1, namely these are com.github.jnr.* . https://github.com/jnr/jnr-unixsocket/issues/95 points in that direction.

**Comment by akurtakov** [comment] 2022-06-23 16:23
@tony-- Is this smth of interest for you?

**Comment by tony--** [comment] 2022-06-23 21:33
@akurtakov thanks for thinking of me and sharing the opportunity, but I am not interested in Mac silicon support.

**Comment by LorenzoBettini** [comment] 2022-11-09 08:46
Same here. I've just installed Docker app on macOS m1. I can't find a way to let Eclipse Docker tooling aware of Docker.

**Comment by jjohnstn** [comment] 2022-11-09 19:41
I too do not have a Mac to test, but found the following on stackoverflow.

https://stackoverflow.com/questions/44084846/cannot-connect-to-the-docker-daemon-on-macos

If you scroll past the highest proposed solution (old solution), you will find one discussing Docker
having removed the /var/run/docker.sock.  Could you try out the proposed workarounds (one is symlinking
to the new socket location) and report back here?  If it works, we should be able to put together something in
Linux Tools.

**Comment by jjohnstn** [comment] 2022-11-24 21:12
If anyone with an Mac M1 wants to test out a potential patch...

There is an upgrade of jnr-unixsocket needed to add Mac M1 support.  I have built a version of Docker Tooling with an upgraded jnr stack and made a repo available in a download zip.  To get the repo, clone the eclipse-linuxtools/linuxtools-website and download the change from:

https://github.com/eclipse-linuxtools/linuxtools-website/pull/3

Unzip the dockertools-mac-experiment.zip file found in the downloads directory to get the repository.

Go to https://download.eclipse.org/eclipse/downloads/ and download the 4.26 RC1 milestone.  Start the 4.26 RC1 eclipse and add the local repository where you unzipped the zip file above via: Help -> Install New Software... -> Add...   Hit the Local button and add your local repository location.  After successfully adding the repo, choose to install Docker Tools and restart.

Try out Docker Tooling and report back here.

**Comment by smuret** [comment] 2022-12-02 16:43
I've installed Eclipse 4.26RC1 and installed the patched tools as stated by @jjohnstn.
On MacBook Pro M1 with Mac OS X Ventura 13.0.1 and Docker desktop 4.15.0 it seems to work fine. 
The Docker Explorer automatically connected using the docker.sock, all my containers are shown, all images are listed and was able to start containers.

**Comment by LorenzoBettini** [comment] 2022-12-28 08:43
I also confirm that with the patched tools, it works!
Unfortunately, I seem to understand, it didn't make it to 2022-12, did it?
Even worse, installing Docker Tooling from 2022-12 makes it impossible to install the patch because the patched repository contains a version considered older.

**Comment by jjohnstn** [comment] 2023-01-03 17:07
Hi @LorenzoBettini , no, it did not make 2022-12 because it was too late to get into Orbit.  It will be part of 2023-03 M1 next week.  I will make a change which will be part of our nightly builds (should be available by tomorrow).

**Comment by LorenzoBettini** [comment] 2023-01-04 06:04
Hi @jjohnstn and thanks for the update.
I thought you'd also have a separate update site where you release your own updated releases, independently from simrel.

**Comment by jjohnstn** [comment] 2023-01-04 15:35
We have our nightly builds repo when changes are merged which eventually are copied to a milestone repo and used in simrel, plus we also can do our own releases separate of simrel, but we usually only do point releases this way (e.g. 5.9.1, 5.9.2) when there is some major bug in the release.  I ran into some test failures yesterday so the change isn't merged yet until I determine if they are just random or caused by the change.

**Comment by akurtakov** [comment] 2023-01-06 11:39
Latest build is available at https://download.eclipse.org/linuxtools/updates-docker-nightly/ . Please test and report whether its working for you.

**Comment by akurtakov** [comment] 2023-02-07 08:52
No reply usually means things work thus closing. Please reopen with details how/what fails if it still happens for you.

**Closed by akurtakov** 2023-02-07 08:52 UTC

**Comment by tcwan** [comment] 2024-02-01 02:38
Sonoma 14.3, Eclipse 2024-3, Docker for Mac 4.27, on M2 Mini. All software are Aarch64 native.

Docker tooling was working on previous version of Eclipse (2023-9) for this system. However, after I upgraded Eclipse to the latest version (2024-3 for Aarch64), Docker Explorer fails to connect to the Docker socket with the following error:

`An internal error occurred during: "Opening connection 'unix:///var/run/docker.sock'[unix:///var/run/docker.sock]...".
Cannot invoke "String.startsWith(String)" because "s" is null
`

/var/run/docker.sock is linked to the macOS user specific socket. I can check docker images via terminal as usual using 'docker images'
