### ISSUE TITLE
Docker Tooling fails on build for Docker Desktop 4.33 on Apple Silicon macOS

### ISSUE THREAD

**Issue by tcwan** [eclipse-linuxtools/org.eclipse.linuxtools#381] opened 2024-07-31 01:12 UTC
This is a new problem with Docker Tooling in Eclipse 2024-03.
Docker Desktop for macOS was updated to v 4.33, on Sonoma 14.6 running on Apple Silicon (M2 Mini)

Docker Explorer can connect to Docker and display the list of images. The image `jrpi4c` was selected successfully in Project Settings (Build Inside Docker Image in the C/C++ Build->Settings->Container tab)

However, when attempting to build the project using Docker Tooling, the build fails with 

`Image not found: jrpi4c:latest (unix:///var/run/docker.sock)
`
Error logs attached.
[cannot-invoke-plugin.txt](https://github.com/user-attachments/files/16434951/cannot-invoke-plugin.txt)
[failed-retrieve.txt](https://github.com/user-attachments/files/16434957/failed-retrieve.txt)

**Comment by tcwan** [comment] 2024-07-31 01:13
The same issue is exhibited for Eclipse 2024-06, but I reverted to older verison for testing and error log generation

**Comment by jjohnstn** [comment] 2024-07-31 22:08
Hi @tcwan Docker Tooling is in maintenance mode and as such, we do not continually update/test for new Docker releases.  We do not have access to MacOS machines so you may have to help us out if the problem is Mac specific, however,  I see from your failed-retrieve.txt that it is complaining about a missing Container or ContainerConfig field which may be a  change in the latest remote API.  I will take a look to see if it is something we can fix on our end or whether an update is required for our docker-client dependency.

**Comment by jjohnstn** [comment] 2024-08-01 21:42
Hi @tcwan I've done some research.  The problem is caused by the latest version of Docker removing some Json fields that were marked deprecated as of 1.44.  The mandas docker-client still has these fields:

```
public interface ImageInfo {

  @JsonProperty("Id")
  String id();

  @JsonProperty("Parent")
  String parent();

  @JsonProperty("Comment")
  String comment();

  @JsonProperty("Created")
  Date created();

  @Deprecated // as of v1.44
  @JsonProperty("Container")
  @Nullable
  String container();

  @Deprecated // as of v1.44
  @JsonProperty("ContainerConfig")
  @Nullable
  ContainerConfig containerConfig();
```

You'll see that container and containerConfig are mentioned in your trace back.

That said, the preceding is latest mandas docker-client code.  An issue needs to be opened to make these fields optional.  I will open an issue and post here.

**Comment by jjohnstn** [comment] 2024-08-01 21:54
@tcwan I created: https://github.com/dmandalidis/docker-client/issues/765

**Comment by jjohnstn** [comment] 2024-08-16 22:54
Hi @tcwan I just updated Linux Tools to docker-client 8.0.2.  It should fix your problem.  It will be available in our nightly build (likely tomorrow).  Our nightly update site is: https://download.eclipse.org/linuxtools/updates-docker-nightly/.   From there, you can update your Linux Tools Docker support.  It will also be part of next weeks 4.33 M3 C/C++ EPP . I will update with M3 EPP site when available.  From there, you can just download the M3 C/C++ EPP on its own and verify you can bring up the Docker Tooling perspective and perform actions with your current Docker.  I'll close this when you confirm.

**Comment by tcwan** [comment] 2024-08-19 13:39
I was getting wierd conflicts when trying to update over my existing eclipse install.
Ended up deleting all eclipse related configs (~/.eclipse, ~/eclipse-workspace), and installed 2024-06-R, and then installed the Linux Tools nightly from 2024-08-19.

After restarting Eclipse, Docker Explorer and Project Settings can see and select the relevant Docker Images now.

I believe that the fix has addressed the issue.

**Comment by jjohnstn** [comment] 2024-08-19 20:25
Great, thanks @tcwan for verifying.

**Closed by jjohnstn** 2024-08-19 20:25 UTC
Labels: bug
